name: "GitFlow"
on:
  push:
    branches:
      - "release/[0-9]+.[0-9]+.[0-9]+"
      - "hotfix/[0-9]+.[0-9]+.[0-9]+"
jobs:
  init:
    name: Initialize release
    runs-on: ubuntu-latest
    outputs:
      commit: ${{ steps.bump.outputs.commit }}
    steps:
      - name: Get metadata
        id: meta
        if: github.event.created
        run: |
          RELEASE_TAG=$(echo "${{ github.event.ref }}" | awk -F / '{print $4}')
          RELEASE_TYPE=$(echo "${{ github.event.ref }}" | awk -F / '{print $3}')
          echo ::set-output name=release_type::"$RELEASE_TYPE"
          echo ::set-output name=main_pr::"$RELEASE_TYPE/$RELEASE_TAG"
          echo ::set-output name=canary_pr::"canary/$RELEASE_TAG"
          echo ::set-output name=tag_name::"$RELEASE_TAG"
          echo ::set-output name=beta_tag_name::"$RELEASE_TAG-beta"
          echo ::set-output name=release_name::"v$RELEASE_TAG"
      - name: Checkout code
        uses: actions/checkout@v2
        if: github.event.created
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v3
        if: github.event.created
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          git-user-signingkey: true
          git-commit-gpgsign: true
      - name: Create pull request to develop
        uses: repo-sync/pull-request@v2
        if: github.event.created
        with:
          destination_branch: develop
          source_branch: ${{ github.event.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: ${{ steps.meta.outputs.canary_pr }}
          pr_draft: false
          pr_allow_empty: true
      - name: Create pull request to main
        uses: repo-sync/pull-request@v2
        if: github.event.created
        with:
          destination_branch: main
          source_branch: ${{ github.event.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: ${{ steps.meta.outputs.main_pr }}
          pr_draft: false
          pr_allow_empty: true
      - name: Bump version
        id: bump
        if: github.event.created
        run: |
          yarn version --new-version ${{ steps.meta.outputs.tag_name }} --no-git-tag-version
          git add package.json
          if git commit -S --message "Bump to ${{ steps.meta.outputs.release_name }}"; then
            git push
          fi
          echo "::set-output name=commit::$(git rev-parse HEAD)"
      - name: Create tag
        uses: tvdias/github-tagger@v0.0.2
        if: github.event.created
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          tag: ${{ steps.meta.outputs.beta_tag_name }}
          commit-sha: ${{ steps.bump.outputs.commit }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        if: github.event.created
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: ${{ steps.meta.outputs.release_name }}
          tag_name: ${{ steps.bump.outputs.commit }}
          draft: true
          prerelease: true
  test:
    name: Test and lint
    runs-on: ubuntu-latest
    needs: init
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ job.init.outputs.commit || github.event.ref }}
      - name: Setup node
        uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
      - name: Get metadata
        id: meta
        shell: bash
        run: |
          echo ::set-output name=os::"$(echo ${{ runner.os }} | tr '[:upper:]' '[:lower:]')"
          echo ::set-output name=yarn_dir::"$(yarn cache dir)"
          echo ::set-output name=yarn_version::"v$(yarn --version | tr '.' '-')"
          echo ::set-output name=node::"$(node --version | tr '.' '-')"
      - name: Get Yarn cache
        uses: actions/cache@v2
        env:
          cache: cache
        with:
          path: ${{ steps.meta.outputs.yarn_dir }}
          key: ${{ steps.meta.outputs.os }}-yarn-${{ steps.meta.outputs.yarn_version }}-${{ env.cache }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ steps.meta.outputs.os }}-yarn-${{ steps.meta.outputs.yarn_version }}-${{ env.cache }}-
            ${{ steps.meta.outputs.os }}-yarn-${{ steps.meta.outputs.yarn_version }}-
            ${{ steps.meta.outputs.os }}-yarn-
            ${{ steps.meta.outputs.os }}-
      - name: Get node_modules cache
        uses: actions/cache@v2
        env:
          cache: cache
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ steps.meta.outputs.os }}-node-${{ steps.meta.outputs.node }}-${{ env.cache }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ steps.meta.outputs.os }}-node-${{ steps.meta.outputs.node }}-${{ env.cache }}-
            ${{ steps.meta.outputs.os }}-node-${{ steps.meta.outputs.node }}-
            ${{ steps.meta.outputs.os }}-node-
            ${{ steps.meta.outputs.os }}-
      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true' && steps.node-modules-cache.outputs.cache-hit != 'true'
        run: yarn install --production=false --frozen-lockfile
      - name: Lint code
        run: yarn lint
      - name: Unit tests
        run: yarn test
  build:
    name: Build package
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ job.init.outputs.commit || github.event.ref }}
      - name: Setup node
        uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
      - name: Get metadata
        id: meta
        shell: bash
        run: |
          RELEASE_TAG=$(echo "${{ github.event.ref }}" | awk -F / '{print $4}')
          RELEASE_TYPE=$(echo "${{ github.event.ref }}" | awk -F / '{print $3}')
          if jq ".name" package.json | jq 'startswith("@")'; then
            SCOPE=$( jq ".name" package.json | jq -r 'split("/")[0]')
            USER=$( jq ".name" package.json | jq 'split("/")[0]' | jq -r 'ltrimstr("@")' )
            PACKAGE_NAME=$( jq ".name" package.json | jq -r 'split("/")[1]')
            ARTIFACT_NAME="$USER-$PACKAGE_NAME-$RELEASE_TAG"
            echo ::set-output name=scope::"$SCOPE"
            echo ::set-output name=artifact::"$ARTIFACT_NAME"
            echo ::set-output name=zip_file::"$ARTIFACT_NAME.zip"
            echo ::set-output name=tar_file::"$ARTIFACT_NAME.tar.gz"
          else
            SCOPE=""
            USER=${{ github.context.repo.owner }}
            PACKAGE_NAME=$( jq -r ".name" package.json )
            ARTIFACT_NAME="$PACKAGE_NAME-$(echo ${{ needs.setup.outputs.tag_name }})"
            echo ::set-output name=scope::"$SCOPE"
            echo ::set-output name=artifact::"$ARTIFACT_NAME"
            echo ::set-output name=zip_file::"$ARTIFACT_NAME.zip"
            echo ::set-output name=tar_file::"$ARTIFACT_NAME.tar.gz"
          fi
          echo ::set-output name=os::"$(echo ${{ runner.os }} | tr '[:upper:]' '[:lower:]')"
          echo ::set-output name=yarn_dir::"$(yarn cache dir)"
          echo ::set-output name=yarn_version::"v$(yarn --version | tr '.' '-')"
          echo ::set-output name=node::"$(node --version | tr '.' '-')"
      - name: Get Yarn cache
        uses: actions/cache@v2
        env:
          cache: cache
        with:
          path: ${{ steps.meta.outputs.yarn_dir }}
          key: ${{ steps.meta.outputs.os }}-yarn-${{ steps.meta.outputs.yarn_version }}-${{ env.cache }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ steps.meta.outputs.os }}-yarn-${{ steps.meta.outputs.yarn_version }}-${{ env.cache }}-
            ${{ steps.meta.outputs.os }}-yarn-${{ steps.meta.outputs.yarn_version }}-
            ${{ steps.meta.outputs.os }}-yarn-
            ${{ steps.meta.outputs.os }}-
      - name: Get node_modules cache
        uses: actions/cache@v2
        env:
          cache: cache
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ steps.meta.outputs.os }}-node-${{ steps.meta.outputs.node }}-${{ env.cache }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ steps.meta.outputs.os }}-node-${{ steps.meta.outputs.node }}-${{ env.cache }}-
            ${{ steps.meta.outputs.os }}-node-${{ steps.meta.outputs.node }}-
            ${{ steps.meta.outputs.os }}-node-
            ${{ steps.meta.outputs.os }}-
      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true' && steps.node-modules-cache.outputs.cache-hit != 'true'
        run: yarn install --production=false --frozen-lockfile
      - name: Build code
        run: yarn bundle
      - uses: actions/upload-artifact@v2
        name: Upload artifact
        with:
          name: ${{ steps.meta.outputs.artifact }}
          path: dist/**/**
  release:
    name: Release
    needs: [init, test, build]
    if: github.event.release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ job.setup.outputs.commit || github.event.ref }}
      - name: Setup node
        uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
          scope: ${{ job.build.outputs.scope }}
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ job.build.outputs.artifact }}
          path: package
      - name: Zip module
        uses: papeloto/action-zip@v1
        with:
          files: package
          recursive: true
          dest: ${{ job.build.outputs.zip_file }}
      - name: Pack module
        run: npm pack ./package
      - name: Tag Repo
        uses: richardsimko/update-tag@v1
        with:
          tag_name: ${{ job.setup.outputs.beta_tag_name }}
      - name: Upload release assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ job.build.outputs.zip_file }}
          asset_name: ${{ job.build.outputs.zip_file }}
          tag: ${{ job.setup.outputs.beta_tag_name }}
          overwrite: true
  publish:
    name: Publish
    needs: [init, test, build, release]
    if: github.event.release
    runs-on: ubuntu-latest
    steps:
      - name: Publish to GitHub Packages
        run: |
          npm config set registry https://npm.pkg.github.com/
          npm publish --access public --dry-run ./package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GHP_TOKEN }}
      - name: Publish to npm
        run: |
          npm config set registry https://registry.npmjs.org/
          npm publish --access public --dry-run ./package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  cleanup:
    name: Clean up release
    runs-on: ubuntu-latest
    if: github.event.deleted
    steps:
      - name: Get metadata
        id: meta
        run: |
          RELEASE_TAG=$(echo "${{ github.event.ref }}" | awk -F / '{print $4}')
          RELEASE_TYPE=$(echo "${{ github.event.ref }}" | awk -F / '{print $3}')
          echo ::set-output name=release_type::"$RELEASE_TYPE"
          echo ::set-output name=main_pr::"$RELEASE_TYPE/$RELEASE_TAG"
          echo ::set-output name=canary_pr::"canary/$RELEASE_TAG"
          echo ::set-output name=tag_name::"$RELEASE_TAG"
          echo ::set-output name=beta_tag_name::"$RELEASE_TAG-beta"
          echo ::set-output name=release_name::"v$RELEASE_TAG"
      - name: Get beta tag
        id: beta_tag
        uses: octokit/graphql-action@v2.x
        env:
          GITHUB_TOKEN: ${{ secrets.GHP_TOKEN }}
        with:
          query: |
            query GetBetaRelease($owner: String!, $repo: String!) {
              repository(owner: $owner, name: $repo) {
                ref(qualifiedName: "2.0.0-beta") {
                  id
                }
              }
            }
          owner: ${{ github.event.repository.owner.name }}
          repo: ${{ github.event.repository.name }}
      - name: Delete beta tag
        uses: octokit/graphql-action@v2.x
        if: fromJson(steps.beta_tag.outputs.data).data.repository.ref.id
        env:
          GITHUB_TOKEN: ${{ secrets.GHP_TOKEN }}
        with:
          query: |
            mutation DeleteBetaTag($tagId: String!) {
              deleteRef(input: {refId: $tagId}) {
                clientMutationId
              }
            }
          tagId: ${{ fromJson(steps.beta_tag.outputs.data).data.repository.ref.id }}
