name: "GitFlow"
on:
  create:
    branches:
      - "release/[0-9]+.[0-9]+.[0-9]+"
      - "hotfix/[0-9]+.[0-9]+.[0-9]+"
jobs:
  setup:
    name: Setup release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get metadata
        id: meta
        shell: bash
        run: |
          RELEASE_TYPE=$(echo "$GITHUB_REF" | awk -F / '{print $3}')
          RELEASE_TAG=$(echo "$GITHUB_REF" | awk -F / '{print $4}')
          echo ::set-output name=type::"$RELEASE_TYPE"
          echo ::set-output name=semver::"$RELEASE_TAG"
          echo ::set-output name=version::"v$RELEASE_TAG"
          echo ::set-output name=branch::"$RELEASE_TYPE/$RELEASE_TAG"
          echo ::set-output name=canary::"canary/$RELEASE_TAG"
      - name: Bump version
        run: |
          git config user.name "Github Actions"
          git config user.email github-actions[bot]@users.noreply.github.com
          yarn version --new-version ${{ steps.meta.outputs.semver }} --no-git-tag-version
          git add package.json
          git commit --message "Bump to ${{ steps.meta.outputs.version }}"
          echo "::set-output name=commit::$(git rev-parse HEAD)"
          git push
      - name: Create pull request to develop
        id: pull-request-develop
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: develop
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: ${{ steps.meta.outputs.canary }}
          pr_draft: false
          pr_allow_empty: true
      - name: Create pull request to main
        id: pull-request-main
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: ${{ steps.meta.outputs.branch }}
          pr_draft: false
          pr_allow_empty: true
