name: "GitFlow"
on:
  push:
    branches:
      - "release/[0-9]+.[0-9]+.[0-9]+"
      - "hotfix/[0-9]+.[0-9]+.[0-9]+"
    tags:
      - "[0-9]+.[0-9]+.[0-9]"
  release:
    types: [prereleased]
jobs:
  setup:
    name: Setup release
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.meta.outputs.tag_name }}
      release_type: ${{ steps.meta.outputs.release_type }}
      release_name: ${{ steps.meta.outputs.release_name }}
      main_pr: ${{ steps.meta.outputs.main_pr }}
      canary_pr: ${{ steps.meta.outputs.canary_pr }}
      zip_file: ${{ steps.meta.outputs.zip_file }}
      tar_file: ${{ steps.meta.outputs.tar_file }}
      commit: ${{ steps.bump.outputs.commit }}
      run_type: ${{ steps.bump.outputs.run_type }}
    steps:
      - name: Get metadata
        id: meta
        shell: bash
        run: |
          if ${{ github.event_name == 'push' }}; then
            RELEASE_TAG=$(echo "${{ github.event.ref }}" | awk -F / '{print $4}')
          fi
          RELEASE_TYPE=$(echo "${{ github.event.ref }}" | awk -F / '{print $3}')
          echo ::set-output name=release_type::"$RELEASE_TYPE"
          echo ::set-output name=main_pr::"$RELEASE_TYPE/$RELEASE_TAG"
          echo ::set-output name=canary_pr::"canary/$RELEASE_TAG"
          echo ::set-output name=tag_name::"$RELEASE_TAG"
          echo ::set-output name=beta_tag_name::"$RELEASE_TAG-beta"
          echo ::set-output name=release_name::"v$RELEASE_TAG"
          if ${{ github.event_name == 'push' && startsWith(github.event.ref, 'refs/heads/') && github.event.created == 1 }}; then
            echo ::set-output name=run_type::"first_push"
          elif ${{ github.event_name == 'push' && startsWith(github.event.ref, 'refs/heads/') && github.event.deleted == 1 }}; then
            echo ::set-output name=run_type::"cleanup"
          fi
      - name: Setup node
        uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
      - name: Query releases
        id: get_releases
        if: steps.meta.outputs.run_type == 'first_push'
        uses: octokit/graphql-action@v2.x
        env:
          GITHUB_TOKEN: ${{ secrets.GHP_TOKEN }}
        with:
          query: |
            query release($owner: String!, $repo: String!) {
              repository(owner: $owner, name: $repo) {
                releases(last: 20) {
                  nodes {
                    tagName
                    isDraft
                    isPrerelease
                    name
                    id
                  }
                }
              }
            }
          owner: ${{ github.event.repository.owner.name }}
          repo: ${{ github.event.repository.name }}
      - name: Get release
        id: get_release
        if: steps.meta.outputs.run_type == 'first_push'
        shell: bash
        run: |
          echo ::set-output name=release::"$(echo '${{ steps.get_releases.outputs.data }}' | jq --arg version ${{ steps.meta.outputs.release_name }} --compact-output '.repository.releases.nodes | map(select(.name | contains($version)))[0]')"
      - name: Delete draft release
        if: steps.meta.outputs.run_type == 'first_push' && steps.get_release.output.release
        run: |
          echo "hello, world"
      - name: Checkout code
        uses: actions/checkout@v2
        if: ${{ steps.meta.outputs.run_type == 'first_push'}}
  test:
    name: Test and lint
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ job.setup.outputs.commit || github.event.ref }}
      - name: Setup node
        uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
      - name: Get metadata
        id: meta
        shell: bash
        run: |
          echo ::set-output name=os::"$(echo ${{ runner.os }} | tr '[:upper:]' '[:lower:]')"
          echo ::set-output name=yarn_dir::"$(yarn cache dir)"
          echo ::set-output name=yarn_version::"v$(yarn --version | tr '.' '-')"
          echo ::set-output name=node::"$(node --version | tr '.' '-')"
      - name: Get Yarn cache
        uses: actions/cache@v2
        env:
          cache: cache
        with:
          path: ${{ steps.meta.outputs.yarn_dir }}
          key: ${{ steps.meta.outputs.os }}-yarn-${{ steps.meta.outputs.yarn_version }}-${{ env.cache }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ steps.meta.outputs.os }}-yarn-${{ steps.meta.outputs.yarn_version }}-${{ env.cache }}-
            ${{ steps.meta.outputs.os }}-yarn-${{ steps.meta.outputs.yarn_version }}-
            ${{ steps.meta.outputs.os }}-yarn-
            ${{ steps.meta.outputs.os }}-
      - name: Get node_modules cache
        uses: actions/cache@v2
        env:
          cache: cache
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ steps.meta.outputs.os }}-node-${{ steps.meta.outputs.node }}-${{ env.cache }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ steps.meta.outputs.os }}-node-${{ steps.meta.outputs.node }}-${{ env.cache }}-
            ${{ steps.meta.outputs.os }}-node-${{ steps.meta.outputs.node }}-
            ${{ steps.meta.outputs.os }}-node-
            ${{ steps.meta.outputs.os }}-
      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true' && steps.node-modules-cache.outputs.cache-hit != 'true'
        run: yarn install --production=false --frozen-lockfile
      - name: Lint code
        run: yarn lint
      - name: Unit tests
        run: yarn test
  build:
    name: Build package
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ job.setup.outputs.commit || github.event.ref }}
      - name: Setup node
        uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
      - name: Get metadata
        id: meta
        shell: bash
        run: |
          if jq ".name" package.json | jq 'startswith("@")'; then
            SCOPE=$( jq ".name" package.json | jq -r 'split("/")[0]')
            USER=$( jq ".name" package.json | jq 'split("/")[0]' | jq -r 'ltrimstr("@")' )
            PACKAGE_NAME=$( jq ".name" package.json | jq -r 'split("/")[1]')
            ARTIFACT_NAME="$USER-$PACKAGE_NAME-$(echo ${{ needs.setup.outputs.tag_name }})"
            echo ::set-output name=scope::"$SCOPE"
            echo ::set-output name=artifact::"$ARTIFACT_NAME"
            echo ::set-output name=zip_file::"$ARTIFACT_NAME.zip"
            echo ::set-output name=tar_file::"$ARTIFACT_NAME.tar.gz"
          else
            SCOPE=""
            USER=${{ github.context.repo.owner }}
            PACKAGE_NAME=$( jq -r ".name" package.json )
            ARTIFACT_NAME="$PACKAGE_NAME-$(echo ${{ needs.setup.outputs.tag_name }})"
            echo ::set-output name=scope::"$SCOPE"
            echo ::set-output name=artifact::"$ARTIFACT_NAME"
            echo ::set-output name=zip_file::"$ARTIFACT_NAME.zip"
            echo ::set-output name=tar_file::"$ARTIFACT_NAME.tar.gz"
          fi
          echo ::set-output name=os::"$(echo ${{ runner.os }} | tr '[:upper:]' '[:lower:]')"
          echo ::set-output name=yarn_dir::"$(yarn cache dir)"
          echo ::set-output name=yarn_version::"v$(yarn --version | tr '.' '-')"
          echo ::set-output name=node::"$(node --version | tr '.' '-')"
      - name: Get Yarn cache
        uses: actions/cache@v2
        env:
          cache: cache
        with:
          path: ${{ steps.meta.outputs.yarn_dir }}
          key: ${{ steps.meta.outputs.os }}-yarn-${{ steps.meta.outputs.yarn_version }}-${{ env.cache }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ steps.meta.outputs.os }}-yarn-${{ steps.meta.outputs.yarn_version }}-${{ env.cache }}-
            ${{ steps.meta.outputs.os }}-yarn-${{ steps.meta.outputs.yarn_version }}-
            ${{ steps.meta.outputs.os }}-yarn-
            ${{ steps.meta.outputs.os }}-
      - name: Get node_modules cache
        uses: actions/cache@v2
        env:
          cache: cache
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ steps.meta.outputs.os }}-node-${{ steps.meta.outputs.node }}-${{ env.cache }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ steps.meta.outputs.os }}-node-${{ steps.meta.outputs.node }}-${{ env.cache }}-
            ${{ steps.meta.outputs.os }}-node-${{ steps.meta.outputs.node }}-
            ${{ steps.meta.outputs.os }}-node-
            ${{ steps.meta.outputs.os }}-
      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true' && steps.node-modules-cache.outputs.cache-hit != 'true'
        run: yarn install --production=false --frozen-lockfile
      - name: Build code
        run: yarn bundle
      - uses: actions/upload-artifact@v2
        name: Upload artifact
        with:
          name: ${{ steps.meta.outputs.artifact }}
          path: dist/**/**
  release:
    name: Release
    needs: [setup, test, build]
    if: github.event.release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ job.setup.outputs.commit || github.event.ref }}
      - name: Setup node
        uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
          scope: ${{ job.build.outputs.scope }}
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ job.build.outputs.artifact }}
          path: package
      - name: Zip module
        uses: papeloto/action-zip@v1
        with:
          files: package
          recursive: true
          dest: ${{ job.build.outputs.zip_file }}
      - name: Pack module
        run: npm pack ./package
      - name: Tag Repo
        uses: richardsimko/update-tag@v1
        with:
          tag_name: ${{ job.setup.outputs.beta_tag_name }}
      - name: Upload release assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ job.build.outputs.zip_file }}
          asset_name: ${{ job.build.outputs.zip_file }}
          tag: ${{ job.setup.outputs.beta_tag_name }}
          overwrite: true
  publish:
    name: Publish
    needs: [setup, test, build, release]
    if: github.event.release
    runs-on: ubuntu-latest
    steps:
      - name: Publish to GitHub Packages
        run: |
          npm config set registry https://npm.pkg.github.com/
          npm publish --access public --dry-run ./package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GHP_TOKEN }}
      - name: Publish to npm
        run: |
          npm config set registry https://registry.npmjs.org/
          npm publish --access public --dry-run ./package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
